### ISSUE TITLE
Port could not be cast to integer

### ISSUE THREAD

**Issue by fosstube** [jvstein/bitcoin-prometheus-exporter#24]
Running this either with or without docker, I get a type conversion error:

```
./bitcoind-monitor.py 
2022-01-12T07:53:19Z INFO Using config file: <default>
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "./bitcoind-monitor.py", line 362, in refresh_app
    refresh_metrics()
  File "./bitcoind-monitor.py", line 246, in refresh_metrics
    uptime = int(bitcoinrpc("uptime"))
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/riprova/retry.py", line 129, in wrapper
    return retrier.run(fn, *args, **_kw)
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/riprova/retrier.py", line 291, in run
    self._handle_error(err)
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/riprova/retrier.py", line 232, in _handle_error
    raise err
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/riprova/retrier.py", line 288, in run
    return self._call(fn, *args, **kw)
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/riprova/retrier.py", line 162, in _call
    res = fn(*args, **kw)
  File "./bitcoind-monitor.py", line 207, in bitcoinrpc
    result = rpc_client().call(*args)
  File "./bitcoind-monitor.py", line 194, in rpc_client
    return rpc_client_factory()()
  File "./bitcoind-monitor.py", line 182, in <lambda>
    return lambda: Proxy(btc_conf_file=BITCOIN_CONF_PATH, timeout=TIMEOUT)
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/bitcoin/rpc.py", line 353, in __init__
    super(Proxy, self).__init__(service_url=service_url,
  File "/opt/bitcoind_exporter/.venv/prometheus_client/lib/python3.8/site-packages/bitcoin/rpc.py", line 196, in __init__
    if self.__url.port is None:
  File "/usr/lib/python3.8/urllib/parse.py", line 174, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '28256:8332'
```
docker-compose.yml (relevant part)
```
    environment:
      BITCOIN_RPC_HOST: 172.28.1.5
      BITCOIN_RPC_PORT: 28256
      BITCOIN_RPC_USER: redacted
      BITCOIN_RPC_PASSWORD: redacted
```
bitcoin.conf (bitcoind is in a samourai dojo container)
```
[main]
rpcconnect=172.28.1.5:28256
rpcuser=redacted
rpcpassword=redacted
```
I've also tried removing the `rpcconnect` line from bitcoin.conf to no effect.

If anyone reading this has the exporter working, please share the pip list so I can see what library versions you're running. I would define versions in the Dockerfile to get a predictable outcome.

**Comment by jvstein** [comment]
@fosstube I suspect you're running into that problem because your `rpcconnect` value has a port number on it.

The project uses the `python-bitcoinlib` library and it expects the config to use `rpcconnect` and `rpcport`, not just the one.

https://github.com/petertodd/python-bitcoinlib/blob/637d2dd9d7f4acf0949a6074fde3869fc06dedf0/bitcoin/rpc.py#L177-L180

**Comment by jvstein** [comment]
Your log seems to indicate that `use_conf == True`. Do you have `BITCOIN_CONF_PATH=""` set in your environment, by chance?

https://github.com/jvstein/bitcoin-prometheus-exporter/blob/5400c9ccf5457498d8ad0ced05a23aed9c566701/bitcoind-monitor.py#L174-L181

**Comment by jvstein** [comment]
This is what I have in my most recently built docker image. The only difference with the latest versions is `prometheus-client==0.12.0` on a fresh virtualenv.

```
prometheus-client==0.11.0
python-bitcoinlib==0.11.0
riprova==0.2.7
six==1.16.0
```

**Comment by fosstube** [comment]
> @fosstube I suspect you're running into that problem because your `rpcconnect` value has a port number on it.
> 
> The project uses the `python-bitcoinlib` library and it expects the config to use `rpcconnect` and `rpcport`, not just the one.

Ah, that was the issue. I wasn't using rpcport and appending the port using rpcconnect.
```
[main]
rpcconnect=172.28.1.5
rpcport=28256
```

Thank you!

**Comment by indrekj** [comment]
I had a similar error and the issue was that my rpc password included `/` character. Writing it here in case somebody stumbles on the same issue.
